import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { Toaster } from 'sonner';

import { CoverImageModal } from '@/components/modals/cover-image-modal';

import { ConvexClientProvider } from '@/providers/convex-client-provider';
import { EdgeStoreProvider } from '@/providers/edgestore-provider';
import { cn } from '@/lib/utils';

import './globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Notion Clone',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico', href: '/favicon.ico' }],
  },
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ConvexClientProvider>
          <EdgeStoreProvider>
            <CoverImageModal />
            {children}
          </EdgeStoreProvider>
        </ConvexClientProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
};

export default RootLayout;
